mutation UpdateFile($data: UpdateFile!) {
  updateFile(data: $data) {
    _id
    approvedBy
    comments {
      _id
      comment
      createdAt
      createdBy
    }
    createdAt
    deletedAt
    extension
    isDeleted
    nameFile
    path
    size
    type
    updatedAt
    uploadedBy {
      _id
      createdAt
      deletedAt
      department
      email
      firstName
      gender
      isDeleted
      lastName
      middleName
      password
      rfc
      roles
      updatedAt
    }
  }
}

mutation UpdateFile($data: UpdateFile!) {
  updateFile(data: $data) {
    _id
    approvedBy
    comments {
      _id
      comment
      createdAt
      createdBy
    }
    createdAt
    deletedAt
    extension
    isDeleted
    nameFile
    path
    size
    type
    updatedAt
    uploadedBy {
      _id
      createdAt
      deletedAt
      department
      email
      firstName
      gender
      isDeleted
      lastName
      middleName
      password
      rfc
      roles
      updatedAt
    }
  }
}

mutation CreateFileComment($data: CreateFileCommentInput!) {
  createFileComment(data: $data) {
    _id
    approvedBy
    comments {
      _id
      comment
      createdAt
      createdBy
    }
    createdAt
    deletedAt
    extension
    attendanceJustified
    isDeleted
    nameFile
    path
    size
    type
    updatedAt
    uploadedBy {
      _id
      createdAt
      deletedAt
      department
      email
      firstName
      gender
      isDeleted
      lastName
      middleName
      password
      rfc
      roles
      updatedAt
    }
  }
}

mutation ApproveFile($data: ApproveFileInput!) {
  approveFile(data: $data) {
    _id
    approvedBy
    comments {
      _id
      comment
      createdAt
      createdBy
    }
    createdAt
    deletedAt
    extension
    isDeleted
    nameFile
    path
    size
    type
    updatedAt
    uploadedBy {
      _id
      createdAt
      deletedAt
      department
      email
      firstName
      gender
      isDeleted
      lastName
      middleName
      password
      rfc
      roles
      updatedAt
    }
  }
}
