query GetAllFiles($filter: FileArgs, $limit: Int, $offset: Int, $page: Int) {
  getAllFiles(filter: $filter, limit: $limit, offset: $offset, page: $page) {
    docs {
      _id
      approvedBy
      comments {
        _id
        comment
        createdAt
        createdBy
      }
      createdAt
      deletedAt
      extension
      isDeleted
      nameFile
      attendanceJustified
      path
      size
      type
      updatedAt
      uploadedBy {
        _id
        createdAt
        deletedAt
        department
        email
        firstName
        gender
        isDeleted
        lastName
        middleName
        password
        rfc
        roles
        updatedAt
      }
    }
    hasNextPage
    hasPrevPage
    limit
    nextPage
    offset
    page
    pagingCounter
    prevPage
    totalDocs
    totalPages
  }
}

query GetFileById {
  getFileById {
    _id
    approvedBy
    comments {
      _id
      comment
      createdAt
      createdBy
    }
    createdAt
    deletedAt
    extension
    isDeleted
    nameFile
    path
    size
    type
    updatedAt
    uploadedBy {
      _id
      createdAt
      deletedAt
      department
      email
      firstName
      gender
      isDeleted
      lastName
      middleName
      password
      rfc
      roles
      updatedAt
    }
  }
}