query GetAllDepartments($filter: DepartmentArgs, $page: Int, $offset: Int, $limit: Int) {
  getAllDepartments(filter: $filter, page: $page, offset: $offset, limit: $limit) {
    docs {
      _id
      createdAt
      deletedAt
      isDeleted
      name
      updatedAt
    }
    hasNextPage
    hasPrevPage
    limit
    nextPage
    offset
    page
    pagingCounter
    prevPage
    totalDocs
    totalPages
  }
}

query GetDepartmentById($id: ID) {
  getDepartmentById(_id: $id) {
    _id
    areaKey
    createdAt
    deletedAt
    isDeleted
    name
    updatedAt
  }
}
