query GetAllCareers($filter: CareerArgs, $limit: Int, $offset: Int, $page: Int) {
  getAllCareers(filter: $filter, limit: $limit, offset: $offset, page: $page) {
    docs {
      _id
      abbreviationCareer
      createdAt
      credits
      deletedAt
      description
      duration
      isCertified
      isDeleted
      name
      updatedAt
    }
    hasNextPage
    hasPrevPage
    limit
    nextPage
    offset
    page
    pagingCounter
    prevPage
    totalDocs
    totalPages
  }
}

query GetCareerById($id: ID) {
  getCareerById(_id: $id) {
    _id
    abbreviationCareer
    createdAt
    credits
    deletedAt
    description
    duration
    isCertified
    isDeleted
    name
    updatedAt
  }
}
