query GetInstituteById($id: ID) {
  getInstituteById(_id: $id) {
    Logo
    _id
    abbreviation
    adress {
      address
      city
      postalCode
      state
      suburb
    }
    createdAt
    deletedAt
    isDeleted
    level
    location {
      address
      city
      postalCode
      state
      suburb
    }
    name
    principallName {
      firstName
      lastName
      secondLastName
    }
    totalHours
    updatedAt
  }
}
