mutation CreateSchedule($data: UpsertScheduleInput!) {
  createSchedule(data: $data) {
    _id
    createdAt
    deletedAt
    finalTime
    classGroup
    isDeleted
    period
    teacher
    startTime
    subject
    updatedAt
  }
}

mutation UpdateSchedule($data: UpdateScheduleInput!) {
  updateSchedule(data: $data) {
    _id
    createdAt
    deletedAt
    finalTime
    classGroup
    isDeleted
    period
    teacher
    startTime
    subject
    updatedAt
  }
}

mutation DeleteSchedule($data: ScheduleIdArgs!) {
  deleteSchedule(data: $data) {
    deleted
  }
}
