mutation CreateCareer($data: CreateCareerInput!) {
  createCareer(data: $data) {
    _id
    abbreviationCareer
    createdAt
    credits
    deletedAt
    description
    duration
    isCertified
    isDeleted
    name
    updatedAt
  }
}

mutation UpdateCareer($data: UpdateCareerInput!) {
  updateCareer(data: $data) {
    _id
    abbreviationCareer
    createdAt
    credits
    deletedAt
    description
    duration
    isCertified
    isDeleted
    name
    updatedAt
  }
}

mutation DeletedCareer($data: CareerIdArgs!) {
  deletedCareer(data: $data) {
    deleted
  }
}