query GetAllGroups($filter: GroupArgs, $limit: Int, $offset: Int, $page: Int) {
  getAllGroups(filter: $filter, limit: $limit, offset: $offset, page: $page) {
    docs {
      _id
      career
      createdAt
      deletedAt
      identifier
      isDeleted
      period
      semester
      updatedAt
    }
    hasNextPage
    hasPrevPage
    limit
    nextPage
    offset
    page
    pagingCounter
    prevPage
    totalDocs
    totalPages
  }
}

query GetGroupById($id: ID) {
  getGroupById(_id: $id) {
    _id
    career
    createdAt
    deletedAt
    identifier
    isDeleted
    period
    semester
    updatedAt
  }
}
