mutation CreateOrganization($data: createOrganizationInput!) {
  createOrganization(data: $data) {
    name
    abbreviationOrg
    vacancyNumbers
    phoneNumber
    numProyect
    location {
      suburb
      state
      postalCode
      city
      address
    }
    emailOrg
  }
}

mutation RemoveOrganization($data: OrganizationIdArgs!) {
  removeOrganization(data: $data) {
    deleted
  }
}

mutation UpdateOrganization($data: UpdateOrganizationInput!) {
  updateOrganization(data: $data) {
    abbreviationOrg
    createdAt
    deletedAt
    emailOrg
    isDeleted
    location {
      address
      city
      postalCode
      state
      suburb
    }
    name
    numProyect
    phoneNumber
    updatedAt
    vacancyNumbers
  }
}
