query Query($id: ID) {
  getOrganizationById(_id: $id) {
    name
    abbreviationOrg
  }
}

query GetOrganizationById($id: ID) {
  getOrganizationById(_id: $id) {
    name
    phoneNumber
    numProyect
  }
}

query GetAllOrganizations {
  getAllOrganizations {
    docs {
      name
      _id
      vacancyNumbers
      updatedAt
      phoneNumber
      numProyect
      location {
        state
        suburb
        postalCode
        city
        address
      }
      isDeleted
      emailOrg
      deletedAt
      createdAt
      abbreviationOrg
    }
  }
}
