query GetAllBuildings($filter: BuildingArgs, $limit: Int, $offset: Int, $page: Int) {
  getAllBuildings(filter: $filter, limit: $limit, offset: $offset, page: $page) {
    docs {
      _id
      createdAt
      deletedAt
      isDeleted
      letter
      name
      updatedAt
    }
    hasNextPage
    hasPrevPage
    limit
    nextPage
    offset
    page
    pagingCounter
    prevPage
    totalDocs
    totalPages
  }
}

query GetBuildingById($id: ID) {
  getBuildingById(_id: $id) {
    _id
    createdAt
    deletedAt
    isDeleted
    letter
    name
    updatedAt
  }
}
