mutation DeleteUser($data: UserIdArgs!) {
  deleteUser(data: $data) {
    deleted
  }
}

mutation UpdateUser($data: UpdateUserInput!) {
  updateUser(data: $data) {
    _id
    createdAt
    deletedAt
    department
    email
    firstName
    gender
    isDeleted
    lastName
    middleName
    password
    rfc
    roles
    photo
    updatedAt
  }
}

mutation UpsertUser($data: UpsertUserInput!) {
  upsertUser(data: $data) {
    _id
    createdAt
    deletedAt
    department
    email
    firstName
    gender
    isDeleted
    lastName
    middleName
    password
    rfc
    roles
    photo
    updatedAt
  }
}